### Create index
PUT http://localhost:3333/indexes/products
Content-Type: application/json

{
  "fields": [
    {"fieldName": "title", "sType": "Text"},
    {"fieldName": "category", "sType": "Keyword"},
    {"fieldName": "organic", "sType": "Bool"},
    {"fieldName": "price", "sType": "Number"}
  ]
}

### Create another index
PUT http://localhost:3333/indexes/items
Content-Type: application/json

{
  "fields": [
    {"fieldName": "title", "sType": "Text"},
    {"fieldName": "optionalField", "sType": "Text", "required" : false}
  ]
}

### flush state
POST http://localhost:3333/flush-state
Content-Type: application/json

### Index a document
POST http://localhost:3333/indexes/products/documents
Content-Type: application/json

{
  "title": "Bio Milch 1.5%",
  "category": "dairy",
  "organic": true,
  "price": 1.29
}

### Index in another index
POST http://localhost:3333/indexes/items/documents
Content-Type: application/json

{
  "title": "Test item",
  "optionalField": "ok good"

}

### Index another document
POST http://localhost:3333/indexes/products/documents
Content-Type: application/json

{
  "title": "Haferflocken Bio",
  "category": "cereals",
  "organic": true,
  "price": 1.99
}

### Search
GET http://localhost:3333/indexes/products/search?q=bio

### Search other index
GET http://localhost:3333/indexes/items/search?q=test

### Search multi-term
GET http://localhost:3333/indexes/products/search?q=bio milch

### Create duplicate index (should fail)
PUT http://localhost:3333/indexes/products
Content-Type: application/json

{
  "fields": [
    {"fieldName": "title", "sType": "Text"}
  ]
}

### Invalid index name (should fail)
PUT http://localhost:3333/indexes/!!!invalid
Content-Type: application/json

{
  "fields": [
    {"fieldName": "title", "sType": "Text"}
  ]
}

### Duplicate field names (should fail)
PUT http://localhost:3333/indexes/test
Content-Type: application/json

{
  "fields": [
    {"fieldName": "title", "sType": "Text"},
    {"fieldName": "title", "sType": "Keyword"}
  ]
}
